services:
  watchdog-app:
    build: .
    container_name: watchdog-app
    ports:
      - "8520:8520"
    depends_on:
      - watchdog-db
    volumes:
      # Die Nabelschnur zu Docker:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://watchdog-db:3306/watchdog_db

  watchdog-db:
    image: mariadb:latest
    container_name: watchdog-db
    environment:
      MARIADB_ROOT_PASSWORD: deinpw
      MARIADB_DATABASE: watchdog_db
    ports:
      - "3306:3306"
    volumes:
      # Der Tresor für deine Logs:
      - mariadb_data:/var/lib/mysql

# Hier wird das Volume offiziell bei Docker angemeldet
volumes:
  mariadb_data: