// spring.application.name=Watchdog

#Datenbankverbindung IntelliJ <-> MariaDBContainer
spring.datasource.url=jdbc:mariadb://localhost:3306/watchdog_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#JPA/HIBERNATE Einstellung
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true